# Lecture 7, direct methods for constrained optimization

Direct methods for constrained optimization are also known as *methods of feasible directions*

## Feasible descent directions

Let $S\subset \mathbb R^n$ ($S\neq \emptyset$ closed) and $x^*\in S$. 
**Definition:** The set
$$ D = \{d\in \mathbb R^n: d\neq0,x^*+\alpha d\in S \text{ for all } \alpha\in (0,\delta) \text{ for some } \delta>0\}$$
is called the cone of feasible directions of $S$ in $x^*$.

**Definition:** The set 
$$ F = \{d\in \mathbb R^n: f(x^*+\alpha d)<f(x^*)\text{ for all } \alpha\in (0,\delta) \text{ for some } \delta>0\}$$
is called the cone of descent directions.

**Definition:** The set $F\cap D$ is called the cone of feasible descent directions.

![alt text](images/feasible_descent_directions.svg "Feasible descent directions")

**(Obvious) Theorem:** Consider an optimization problem 
$$
\begin{align}
\min &\  f(x)\\
\text{s.t. }&\ x\in S
\end{align}
$$
and let $x^*\in S$. Now if $x^*$ is a local minimizer **then** the set of feasible descent directions $F\cap D$ is empty.

## Idea for the methods of feasible descent directions

1. Assume a feasible solution $x$.
2. Find a feasible descent direction $d\in D\cap F$.
3. Determine the step length to the direction $d$
4. Update $x$ accordingly.




# Projected gradient method

Assume a problem with linear equality constraints
$$
\min f(x)\\
\text{s.t. }Ax=b,
$$
where $A$ is a $lxn$ matrix ($l\leq n$) and $b$ is a vector.

Let $x$ be a feasible solution to the above problem.

It holds that:

$d$ is a feasible direction *if and only if* $Ad=0$

Thus, the gradient $\nabla f(x)$ is a feasible descent direction, if 
$$ A\nabla f(x)=0.$$

This may or may not be true.

However, we can project the gradient to the set of feasible descent directions
$$ \{d\in \mathbb R^n: Ad=0\},$$
which now is a linear subspace.

### Projection

Let $a\in \mathbb R^n$ be a vector and let $L$ be a linear subspace of $\mathbb R^n$. Now, the following are equivalent
* $a^P$ is the projection of $a$ on $L$,
* $\{a^P\} = \operatorname{argmin}_{l\in L}\|a-l\|$, and
* $a^P\in A$ and $(a-a^P)^Tl=0$ for all $l\in L$.

## Projected gradient

The projection of the gradient $\nabla f(x)$ on the set $\{d\in \mathbb R^n: Ad=0\}$ is denoted by $\nabla f(x)^P$ and called the *projected gradient*. 

Now, given some conditions, the projected gradient gives us a feasible descent direction.

## How to compute the projected gradient?

There are different ways, but at this course we can use optimization. Basically, the optimization problem that we have to solve is
$$
\min \|\nabla f(x)-d\|\\
\text{s.t. }Ad=0.
$$

Since it is equivalent to minimize the square of the objective function, we can see that the problem is a quadratic problem with inequality constraints, which means that we just need to solve the system of equations
$$
\left[
\begin{array}{cc}
0.5*I&A^T\\
A&0
\end{array}
\right] d= \left[ 
\begin{array}{c}
\nabla f(x)\\
0
\end{array}
\right],
$$
where I is the identity matrix.

### Code in Python

A function for projecting a vector to a linear space defined by $Ax=0$.

In [1]:
import numpy as np
def project_vector(A,vector):
    #convert A into a matrix
    A_matrix = np.matrix(A)
    #construct the "first row" of the matrix [[I,A^T],[A,0]]
    left_matrix_first_row = np.concatenate((0.5*np.identity(len(vector)),A_matrix.transpose()), axis=1)
    #construct the "second row" of the matrix
    left_matrix_second_row = np.concatenate((A_matrix,np.matrix(np.zeros([len(A),len(vector)+len(A)-len(A[0])]))), axis=1)
    #combine the whole matrix by combining the rows
    left_matrix = np.concatenate((left_matrix_first_row,left_matrix_second_row),axis = 0)
    #Solve the system of linear equalities from the previous page
    return np.linalg.solve(left_matrix, np.concatenate((np.matrix(vector).transpose(),np.zeros([len(A),1])),axis=0))[:len(vector)]

In [2]:
A = [[1,0]]
gradient = [-1,-1]
project_vector(A,gradient)

matrix([[ 0.],
        [-2.]])

# Example

Let us study optimization problem
$$
\begin{align}
\min \qquad& x_1^2+x_2^2+x_3^2\\
\text{s.t.}\qquad &x_1+x_2=3\\
    &x_1+x_3=4.
\end{align}
$$
Let us project a gradient from a feasible point $x=(1,2,3)$

Now, the matrix
$$
A = \left[
\begin{array}{ccc}
1& 1 & 0\\
1& 0 & 1
\end{array}
\right]
$$.

In [19]:
import ad
A = [[1,1,0],[1,0,1]]
gradient = ad.gh(lambda x:x[0]**2+x[1]**2+x[2]**2)[0]([1,2,3])
d = project_vector(A,[-i for i in gradient])
print d

[[ 5.33333333]
 [-5.33333333]
 [-5.33333333]]


### d is a feasible direction

In [20]:
np.matrix(A)*d

matrix([[ 0.],
        [ 0.]])

In [21]:
def f(x):
    return x[0]**2+x[1]**2+x[2]**2
alpha = 0.001

### d is a descent direction

In [22]:
print "Value of f at [1,2,3] is "+str(f([1,2,3]))
x_mod= np.array([1,2,3])+alpha*np.array(d).transpose()[0]
print "Value of f at [1,2,4] +alpha*d is "+str(f(x_mod))

Value of f at [1,2,3] is 14
Value of f at [1,2,4] +alpha*d is 13.9574186667


## Finally, the algorithm of the projected gradient

In [24]:
import numpy as np
import ad
def projected_gradient_method(f,A,start,step,precision):
    f_old = float('Inf')
    x = np.array(start)
    steps = []
    f_new = f(x)
    while abs(f_old-f_new)>precision:
        f_old = f_new
        gradient = ad.gh(f)[0](x)
        d = project_vector(A,[-i for i in gradient])#The only changes to steepest..
        d = np.array(d.transpose())[0] #... descent are here!
        x = x+d*step
        f_new = f(x)
        steps.append(list(x))
    return x,f_new,steps

In [25]:
f = lambda x:x[0]**2+x[1]**2+x[2]**2
A = [[1,1,0],[1,0,1]]
start = [1,2,3]
(x,f_val,steps) = projected_gradient_method(f,A,start,0.6,0.000001)

/usr/lib/python2.7/site-packages/ad/__init__.py:767: RuntimeWarning: overflow encountered in double_scalars
  qc_wrt_args = [y*(y - 1)*x**(y - 2), x**y*(math.log(x))**2]
/usr/lib/python2.7/site-packages/ad/__init__.py:87: RuntimeWarning: invalid value encountered in double_scalars
  qc_wrt_vars[var1] += dh*f.d2(var1) + d2h*fdv1**2
/usr/lib/python2.7/site-packages/ad/__init__.py:768: RuntimeWarning: overflow encountered in double_scalars
  cp_wrt_args = x**y*(y*math.log(x) + 1)/x
/usr/lib/python2.7/site-packages/ad/__init__.py:97: RuntimeWarning: invalid value encountered in double_scalars
  tmp = 2*cp_wrt_args*ad_funcs[0].d(var1)*ad_funcs[1].d(var1)
/usr/lib/python2.7/site-packages/ad/__init__.py:766: RuntimeWarning: overflow encountered in double_scalars
  lc_wrt_args = [y*x**(y - 1), x**y*math.log(x)]
/usr/lib/python2.7/site-packages/ad/__init__.py:84: RuntimeWarning: invalid value encountered in double_scalars
  lc_wrt_vars[var1] += dh*fdv1


In [149]:
print x
print np.matrix(A)*np.matrix(x).transpose()

[ 2.333248  0.666752  1.666752]
[[ 3.]
 [ 4.]]
